#pragma once
#include <stdint.h>
extern uint32_t _binary_maskmaster_e00_6A00_data_pal_start __asm("_binary_maskmaster_e00_6A00_data_pal_start");
extern uint32_t _binary_maskmaster_e00_6A00_data_pal_end __asm("_binary_maskmaster_e00_6A00_data_pal_end");
extern uint32_t _binary_maskmaster_e00_6A00_data_pal_size __asm("_binary_maskmaster_e00_6A00_data_pal_size");
